<?php

namespace AppBundle\Repository;

/**
 * AdsOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdsOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
