<?php

namespace AppBundle\Repository;

/**
 * AdvancedFieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvancedFieldsRepository extends \Doctrine\ORM\EntityRepository
{
}
