<?php

namespace AppBundle\Repository;

/**
 * BusinessStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessStatsRepository extends \Doctrine\ORM\EntityRepository
{
}
