<?php

namespace AppBundle\Repository;

/**
 * BusinessRequestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessRequestsRepository extends \Doctrine\ORM\EntityRepository
{
}
