<?php

namespace AppBundle\Repository;

/**
 * comuniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class comuniRepository extends \Doctrine\ORM\EntityRepository
{
}
