import { Router } from 'express';
import { adminController } from '../controllers/admin.controller';
import { adminCrmController } from '../controllers/admin-crm.controller';
import { adminExportController } from '../controllers/admin-export.controller';
import { adminImportController } from '../controllers/admin-import.controller';
import { adminOrdersController } from '../controllers/admin-orders.controller';
import { adminPromotionsController } from '../controllers/admin-promotions.controller';
import { disputesController } from '../controllers/disputes.controller';
import { uploadImage } from '../middleware/upload.middleware';
import { requireAdmin } from '../middleware/auth.middleware';

const router = Router();

router.use(requireAdmin);

router.get('/stats', adminController.getStats);
router.get('/kpi', adminController.getKpi);
router.get('/system', adminController.getSystemInfo);
router.get('/export/users', adminExportController.users);
router.get('/export/ads', adminExportController.ads);
router.get('/export/payments', adminExportController.payments);
router.post('/import/:entity/dry-run', adminImportController.dryRun);
router.get('/promotions/packages', adminPromotionsController.listPackages);
router.post('/promotions/packages', adminPromotionsController.createPackage);
router.put('/promotions/packages/:id', adminPromotionsController.updatePackage);
router.delete('/promotions/packages/:id', adminPromotionsController.deletePackage);
router.get('/promotions', adminPromotionsController.overview);
router.get('/orders', adminOrdersController.list);
router.put('/orders/:id/payment', adminOrdersController.reconcilePayment);
router.get('/users', adminController.listUsers);
router.get('/users/:id/crm', adminCrmController.listUserNotes);
router.post('/users/:id/crm', adminCrmController.createUserNote);
router.put('/users/:id/crm/:noteId', adminCrmController.updateUserNote);
router.get('/users/:id', adminController.getUser);
router.put('/users/:id', adminController.updateUser);
router.delete('/users/:id', adminController.deleteUser);
router.get('/ads', adminController.listAds);
router.get('/ads/:id', adminController.getAd);
router.put('/ads/:id', adminController.updateAd);
router.get('/helpdesk', adminController.listHelpDesk);
router.put('/helpdesk/:id', adminController.updateHelpDesk);
router.post('/helpdesk/:id/reply', adminController.replyHelpDesk);
router.get('/payments/webhook-logs', adminController.listPaymentWebhookLogs);
router.get('/payments', adminController.listPayments);
router.get('/reports', adminController.listReports);
router.put('/reports/:id', adminController.updateReport);
router.get('/disputes', disputesController.adminList);
router.put('/disputes/:id', disputesController.adminUpdate);
router.post('/disputes/:id/messages', uploadImage.array('attachments', 5), disputesController.addMessage);
router.get('/business-requests', adminController.listBusinessRequests);
router.put('/business-requests/:id', adminController.updateBusinessRequest);
router.get('/videos', adminController.listVideos);
router.put('/videos/:id', adminController.updateVideo);
router.get('/reviews', adminController.listReviews);
router.put('/reviews/:id', adminController.updateReview);
router.get('/actions', adminController.listActions);

export default router;
