<?php

namespace AppBundle\Repository;

/**
 * AdminDefaultMailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminDefaultMailsRepository extends \Doctrine\ORM\EntityRepository
{
}
