<?php

namespace AppBundle\Repository;

/**
 * AdminActionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminActionsRepository extends \Doctrine\ORM\EntityRepository
{
}
