<?php

namespace AppBundle\Repository;

/**
 * HelpDeskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelpDeskRepository extends \Doctrine\ORM\EntityRepository
{
}
