<?php

namespace AppBundle\Repository;

/**
 * provinceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class provinceRepository extends \Doctrine\ORM\EntityRepository
{
}
