<?php

namespace AppBundle\Repository;

/**
 * regioniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class regioniRepository extends \Doctrine\ORM\EntityRepository
{
}
