<?php

namespace AppBundle\Repository;

/**
 * SuggestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuggestsRepository extends \Doctrine\ORM\EntityRepository
{
}
