# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    core.amazon_s3.class: AmazonS3
    core_storage.video_uploader.class: LM\Bundle\CoreBundle\Service\PhotoUploader

services:
    app.twig_extension:
        class: AppBundle\Twig\Category
        public: false
        tags:
            - { name: twig.extension }
    app.aws_s3.client:
        class: Aws\S3\S3Client
        factory: [Aws\S3\S3Client, 'factory']
        arguments:
            -
                version: latest
                region: %amazon.region%
                credentials:
                    key: %amazon.key%
                    secret: %amazon.secret%
